// Code generated by "stringer -type=Gamer -output=gen_gamer.go -trimprefix=Gamer"; DO NOT EDIT.

package participants

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[GamerUnknown-0]
	_ = x[GamerMike-1]
	_ = x[GamerPaul-2]
	_ = x[GamerDayle-3]
	_ = x[GamerNoone-4]
	_ = x[GamerLockers-5]
	_ = x[GamerKirky-6]
	_ = x[GamerWezz-7]
	_ = x[GamerPiper-8]
	_ = x[GamerJames-9]
	_ = x[GamerDerren-10]
	_ = x[GamerNathan-11]
	_ = x[GamerQck-12]
	_ = x[GamerSantosh-13]
	_ = x[GamerTristan-14]
	_ = x[GamerAlex-15]
	_ = x[GamerLee-16]
	_ = x[GamerTapan-17]
	_ = x[GamerGemima-18]
	_ = x[GamerBayley-19]
}

const _Gamer_name = "UnknownMikePaulDayleNooneLockersKirkyWezzPiperJamesDerrenNathanQckSantoshTristanAlexLeeTapanGemimaBayley"

var _Gamer_index = [...]uint8{0, 7, 11, 15, 20, 25, 32, 37, 41, 46, 51, 57, 63, 66, 73, 80, 84, 87, 92, 98, 104}

func (i Gamer) String() string {
	if i < 0 || i >= Gamer(len(_Gamer_index)-1) {
		return "Gamer(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Gamer_name[_Gamer_index[i]:_Gamer_index[i+1]]
}
